from core.metadata import Metadata
from core.mw import MappingWrapper

class MusicDb(Metadata, MappingWrapper):
    """Base class for metadata derived from a database/data file, e.g. one generated by a music player."""

    def __init__(self, d):
        MappingWrapper.__init__(self, d)
